# Generated by Django 5.2 on 2025-05-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostic",
            name="report_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="diagnostic_date",
            field=models.DateField(),
        ),
    ]
