# Generated by Django 5.2 on 2025-05-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychology", "0002_diagnostic_report_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
