# Generated by Django 5.2 on 2025-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_parents_students_delete_student_parents_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
