# Generated by Django 5.2 on 2025-05-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_alter_students_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="parents",
            name="parent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
