# Generated by Django 5.2 on 2025-05-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_parents_parent_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Parents",
            new_name="Parent",
        ),
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
    ]
